import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Frame from './Frame';
import RowProvider from '../store/RowProvider';
import SolutionsProvider from '@/store/SolutionsProvider';
import FramelessSolutionsProvider from '@/store/FramelessSolutionsProvider';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RowProvider>
          <SolutionsProvider>
            <FramelessSolutionsProvider>

              <Frame />

            </FramelessSolutionsProvider>
          </SolutionsProvider>
        </RowProvider>
      </main>
    </>
  )
}
